export const localizedContent = {
    en: {
        profile: {
            handle: 'Gralerfics',
            realName: 'Zhuoyang (Julian) Wang',
            title: 'Robotics / Signal Processing / Electronic Engineering',
            location: 'Delft, Netherlands',
            emails: [
                'z.wang-107@student.tudelft.nl',
                'glverfer@outlook.com'
            ],
            github: 'https://github.com/Gralerfics',
            intro: 'An engineering-oriented Master student working across robotics, signal processing, digital design and embedded systems.',
            statement:
                // 'Currently interested in Human-robot interaction and reinforcement learning in robotic control.',
                'Welcome! Please see my resume for more details.',
        },
        researchFocus: [
            'Robotics navigation and control / Human-robot interaction',
            'Machine Learning / Reinforcement Learning',
            'Embedded systems and hardware-software co-design / Digital system design',
            'Computer graphics and rendering',
        ],
        resumeContent: {
            profileStatement: [
                'I am Zhuoyang (Julian) Wang, currently pursuing a Master\'s degree in Electrical Engineering (Signals and Systems track) at TU Delft.',
                'I am comfortable with engineering-driven project development and have solid programming experience. I have worked on multiple robotics projects involving navigation and control, and I am familiar with ROS, Linux and related tools. I have also completed several embedded systems and FPGA projects that involved both hardware and software, with exposure to computer architecture, embedded Linux, and hands-on prototyping for validation.',
                'I am particularly interested in control theory and reinforcement learning in robot motion planning and control and currently looking for a relevant master\'s thesis project or internship.',
            ],
            education: [
                {
                    time: '2025 - Present',
                    title: 'MSc, Electrical Engineering (Signals & Systems Track)',
                    organization: 'Delft University of Technology (TU Delft)',
                    notes: ['The programme is still ongoing.'],
                    courses: [
                        { code: 'EE4C11', name: 'Systems Engineering', grade: '8.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14833' },
                        { code: 'EE4C03', name: 'Statistical Digital Signal Processing and Modelling', grade: '8.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14827' },
                        { code: 'EE4C04', name: 'Control System Design', grade: '10.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14828', featured: true },
                        { code: 'SC42025', name: 'Filtering and Identification', grade: '9.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19214', featured: true },
                        { code: 'EE4530', name: 'Applied Convex Optimisation', grade: '8.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14867' },
                        { code: 'RO47005', name: 'Planning and Decision Making', grade: '9.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19479', featured: true },
                        { code: 'ET4386', name: 'Estimation and Detection', grade: '6.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14948' },
                        { code: 'RO47013', name: 'Control in Human-Robot Interaction', grade: '8.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19483', featured: true },
                        { code: 'RO47021', name: 'Intelligent Control Systems', grade: '10.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/21449', featured: true },
                        { code: 'SC42125', name: 'Model Predictive Control', grade: '7.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19505' },
                        { code: 'EE4740', name: 'Data Compression: Entropy and Sparsity Perspectives', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/14456' },
                        { code: 'SC42110', name: 'Dynamic Programming and Stochastic Control', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/19504' },
                        { code: 'SC42101', name: 'Networked and Distributed Control Systems', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/19503' },
                        { code: 'DSAIT4115', name: 'Deep Reinforcement Learning', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/14811', featured: true },
                    ],
                },
                {
                    time: '2021 - 2025',
                    title: 'BEng, Information Engineering',
                    organization: 'Southern University of Science and Technology (SUSTech)',
                    notes: ['The courses listed are selected.'],
                    courses: [
                        { category: '', items: [{ name: 'Weighted Average Mark', grade: '94.81 / 100' }] },
                        {
                            category: 'Mathematics',
                            items: [
                                { name: 'Mathematical Physics Methods', grade: '97' },
                                { name: 'Linear Algebra', grade: '90' },
                                { name: 'Probability Theory and Mathematical Statistics', grade: '96' },
                                { name: 'Discrete Mathematics', grade: '99' },
                                { name: 'Statistical Learning in Data Science', grade: '97' },
                            ],
                        },
                        {
                            category: 'Physics',
                            items: [
                                { name: 'General Physics I', grade: '98' },
                                { name: 'General Physics II', grade: '90' },
                                { name: 'Engineering Electromagnetic Field Theory', grade: '99' },
                            ],
                        },
                        {
                            category: 'Circuits',
                            items: [
                                { name: 'Fundamentals of Circuits', grade: '99' },
                                { name: 'Analog Circuits', grade: '98' },
                                { name: 'Digital Circuits', grade: '99' },
                                { name: 'Microprocessors and Microsystems', grade: '94' },
                            ],
                        },
                        {
                            category: 'Signals, Systems and Control',
                            items: [
                                { name: 'Signals and Systems', grade: '94' },
                                { name: 'Digital Signal Processing', grade: '98' },
                                { name: 'Digital System Designing', grade: '98' },
                                { name: 'Digital Image Processing', grade: '98' },
                                { name: 'Robotic Motion and Control', grade: '99' },
                                { name: 'Robot Perception and Intelligence', grade: '93' },
                                { name: 'Mobile Robot Navigation and Control', grade: '96' },
                                { name: 'Principles of Communication', grade: '97' },
                                { name: 'AI and Machine Learning', grade: '94' },
                                { name: 'Feedback Control Theory', grade: '95' },
                                { name: 'Information Theory and Coding', grade: '94' },
                            ],
                        },
                    ],
                },
                // {
                //     time: '2018 - 2021',
                //     title: 'High School Diploma',
                //     organization: 'Changzhou Senior High School of Jiangsu Province',
                // },
            ],
            skills: [
                { title: 'Programming', detail: 'Proficient in Python, C, VHDL; experienced with C++, Java; familiar with JavaScript / Vue3, etc.' },
                { title: 'Platform', detail: 'Experienced with Linux, ROS / ROS2, MuJoCo, PyBullet; familiar with PyTorch, JAX, SB3, RLlib; worked with real robotic arms / mobile robots, etc.' },
                { title: 'Embedded', detail: 'Soldering, assembly, PCB design, and hardware debugging; STM32, FPGA, common sensors and modules, RTOS, Linux.' },
                { title: 'Other', detail: 'Adobe Illustrator, SolidWorks.' },
            ],
            honors: [
                { title: 'National First Prize', detail: '2024 National (China) College Embedded Chip and System Design Competition, Application Track' },
                { title: 'Junior Embedded System Design Engineer', detail: 'awarded by Chinese Institute of Electronics (CIE)' },
                { title: 'Second Prize', detail: '2021 Asia and Pacific Mathematical Contest in Modeling' },
            ],
        },
    },
    zh: {
        profile: {
            handle: 'Gralerfics',
            realName: '王卓扬',
            title: '机器人 / 信号处理 / 电子工程',
            location: '代尔夫特，荷兰',
            emails: ['z.wang-107@student.tudelft.nl', 'glverfer@outlook.com'],
            github: 'https://github.com/Gralerfics',
            intro: '对机器人、信号处理、数字设计与嵌入式系统感兴趣的工程导向开发者。',
            statement: '欢迎浏览个人简历查看详情。',
        },
        researchFocus: [
            '机器人导航与控制 / 人机交互',
            '机器学习 / 强化学习',
            '嵌入式系统软硬件设计 / 数字系统设计',
            '计算机图形与物理模拟',
        ],
        resumeContent: {
            profileStatement: [
                '我是王卓扬，目前就读于代尔夫特理工大学电气工程硕士项目，信号与系统方向。',
                '我擅长工程导向的项目开发，具备较丰富的程序设计经验；参与过多个机器人导航与控制项目，熟悉 ROS 等相关技术栈；也做过多个嵌入式 / FPGA 相关的软硬件协同项目，了解计算机组成原理、嵌入式 Linux 等，并且擅长动手做原型验证。',
                '现阶段我感兴趣的是机器人运动控制中的控制理论和强化学习应用，并正在寻找相关的硕士论文项目与实习。',
            ],
            education: [
                {
                    time: '2025 - 至今',
                    title: '电气工程硕士，信号与系统方向',
                    organization: '代尔夫特理工大学（TU Delft）',
                    notes: ['项目仍在进行中。'],
                    courses: [
                        { code: 'EE4C11', name: 'Systems Engineering', grade: '8.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14833' },
                        { code: 'EE4C03', name: 'Statistical Digital Signal Processing and Modelling', grade: '8.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14827' },
                        { code: 'EE4C04', name: 'Control System Design', grade: '10.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14828', featured: true },
                        { code: 'SC42025', name: 'Filtering and Identification', grade: '9.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19214', featured: true },
                        { code: 'EE4530', name: 'Applied Convex Optimisation', grade: '8.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14867' },
                        { code: 'RO47005', name: 'Planning and Decision Making', grade: '9.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19479', featured: true },
                        { code: 'ET4386', name: 'Estimation and Detection', grade: '6.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/14948' },
                        { code: 'RO47013', name: 'Control in Human-Robot Interaction', grade: '8.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19483', featured: true },
                        { code: 'RO47021', name: 'Intelligent Control Systems', grade: '10.0', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/21449', featured: true },
                        { code: 'SC42125', name: 'Model Predictive Control', grade: '7.5', link: 'https://studyguide.tudelft.nl/courses/study-guide/educations/19505' },
                        { code: 'EE4740', name: 'Data Compression: Entropy and Sparsity Perspectives', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/14456' },
                        { code: 'SC42110', name: 'Dynamic Programming and Stochastic Control', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/19504' },
                        { code: 'SC42101', name: 'Networked and Distributed Control Systems', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/19503' },
                        { code: 'DSAIT4115', name: 'Deep Reinforcement Learning', grade: 'ongoing', link: 'https://studiegids.tudelft.nl/courses/study-guide/educations/14811', featured: true },
                    ],
                },
                {
                    time: '2021 - 2025',
                    title: '信息工程学士',
                    organization: '南方科技大学（SUSTech）',
                    notes: ['以上非全部课程。'],
                    courses: [
                        { category: '', items: [{ name: '加权平均分', grade: '94.81 / 100' }] },
                        {
                            category: '数学',
                            items: [
                                { name: '数学物理方法', grade: '97' },
                                { name: '线性代数', grade: '90' },
                                { name: '概率论与数理统计', grade: '96' },
                                { name: '离散数学', grade: '99' },
                            ],
                        },
                        {
                            category: '物理',
                            items: [
                                { name: '大学物理（上）', grade: '98' },
                                { name: '大学物理（下）', grade: '90' },
                                { name: '工程电磁场', grade: '99' },
                            ],
                        },
                        {
                            category: '电路',
                            items: [
                                { name: '电路基础', grade: '99' },
                                { name: '模拟电路', grade: '98' },
                                { name: '数字电路', grade: '99' },
                                { name: '微机原理与微系统', grade: '94' },
                            ],
                        },
                        {
                            category: '信号、系统与控制',
                            items: [
                                { name: '信号与系统', grade: '94' },
                                { name: '数字信号处理', grade: '98' },
                                { name: '数字系统设计', grade: '98' },
                                { name: '数字图像处理', grade: '98' },
                                { name: '机器人运动与控制', grade: '99' },
                                { name: '机器人感知与智能', grade: '93' },
                                { name: '移动机器人导航与控制', grade: '96' },
                                { name: '通信原理', grade: '97' },
                                { name: '自动控制理论', grade: '95' },
                                { name: '人工智能与机器学习', grade: '94' },
                                { name: '数据科学中的统计学习', grade: '97' },
                                { name: '信息论与编码', grade: '94' },
                            ],
                        },
                    ],
                },
                // {
                //     time: '2018 - 2021',
                //     title: '高中学位',
                //     organization: '江苏省常州高级中学',
                // },
            ],
            skills: [
                { title: '程序设计', detail: '熟练掌握 Python、C、VHDL；熟悉 C++、Java；了解 JavaScript / Vue3 等；追求高质量代码与架构。' },
                { title: '平台/框架', detail: '熟悉 Linux、ROS / ROS2 等平台及 PyTorch、JAX、SB3、RLlib 等框架的使用；MuJoCo、PyBullet 等仿真经验；实际机械臂、移动机器人等的调试经验。' },
                { title: '嵌入式', detail: '熟悉微控制器和嵌入式系统（STM32 等）及FPGA开发；嵌入式 Linux、FreeRTOS 使用经验；熟悉焊锡、组装、简单 PCB 设计与硬件调试。' },
                { title: '其他', detail: 'Adobe Illustrator、SolidWorks 等。' },
            ],
            honors: [
                { title: '全国一等奖', detail: '2024 年全国大学生嵌入式芯片与系统设计竞赛（应用赛道）' },
                { title: '初级嵌入式系统设计工程师', detail: '中国电子学会（CIE）认证' },
                { title: '二等奖', detail: '2021 年亚太地区大学生数学建模竞赛' },
            ],
        },
    },
}
